{
 "title": "Aptos",
 "description": "Unofficial SubSquid dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "aptos_state_sync_version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aptos_state_sync_version{job=\"aptos\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "aptos_state_sync_requests_sent_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "aptos_state_sync_requests_sent_total{peer=\"e7be8996\"}"
    }
   ]
  },
  {
   "title": "sqd_archive_chain_height_updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "aptos_connections{}" }
   ]
  },
  {
   "title": "aptos_schemadb_batch_commit_bytes_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{db_name=\"aptosdb\",job=\"aptos\"}"
    }
   ]
  },
  {
   "title": "lost_peer|new_peer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{event=~\"lost_peer|new_peer\",job=\"aptos\"}",
     "legendFormat": "{{squid_chain}}"
    }
   ]
  },
  {
   "title": "aptos_rocksdb_properties",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{cf_name=~\"epoch_by_version|event|event_accumulator|event_by_key|event_by_version|jellyfish_merkle_node|ledger_counters|stale_node_index|transaction|transaction_accumulator|transaction_by_account|transaction_by_hash|transaction_info|write_set\",job=\"aptos\"}",
     "legendFormat": "{{squid_chain}}"
    }
   ]
  },
  {
   "title": "Head block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "{job=\"aptos\",network_id=\"Public\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Nodejs_active_handles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "aptos_connections{network_id=\"Public\"}",
     "legendFormat": "{{squid_chain}}"
    }
   ]
  }
 ]
}